-- Init schema for DLP Tracker (roles + tags)
CREATE TABLE IF NOT EXISTS roles(
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

INSERT INTO roles(name) VALUES ('admin'), ('user')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role_id INTEGER REFERENCES roles(id),
  full_name TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS locations(
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  address TEXT,
  city TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visits(
  id SERIAL PRIMARY KEY,
  location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  material TEXT,
  spent NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tags(
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS visit_tags(
  visit_id INTEGER NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY(visit_id, tag_id)
);

-- demo admin (login: admin / password: admin)
DO $$
DECLARE admin_role_id integer;
BEGIN
  SELECT id INTO admin_role_id FROM roles WHERE name='admin';
  IF admin_role_id IS NULL THEN
    INSERT INTO roles(name) VALUES ('admin') RETURNING id INTO admin_role_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM users WHERE username='admin') THEN
    -- NOTE: password_hash must be generated by the app if you want a real hash here.
    -- This placeholder will be overwritten by the app's ensure_schema seed on first run.
    INSERT INTO users(username, password_hash, role_id, full_name)
    VALUES ('admin', 'PLEASE_LOGIN_AND_RESET', admin_role_id, 'Администратор');
  END IF;
END$$;
